title: <p align="center"> Ahmed Hussain </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://github.com/Ahmed-AIML">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Data Transfomration problems
  Also handing the Big Data from real-time transaction data.
  Worked with Lineage Logistics at Big Data Analytics team.
  Working in Banking domain for 6 years.
  <br>
  </p>



theme: jekyll-theme-minimal